In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import math

In [2]:
df = pd.read_csv("INOHA-DataScience-M2/donnees_epidemiologiques_RDC.csv")
df

,Semaine,RDC,Cas_Suspects,Cas_Confirmes,Pluviometrie_mm,Temperature_C,Deforestation_ha,NDVI
0,S01,RDC,59,26,122,26.5,19.7,0.38
1,S02,RDC,98,43,290,28.2,11.5,0.26
2,S03,RDC,74,35,126,26.0,11.8,0.46
3,S04,RDC,58,34,91,26.2,22.3,0.58
4,S05,RDC,79,36,208,25.4,27.1,0.31
...,...,...,...,...,...,...,...,...
95,S96,RDC,60,31,246,26.2,10.0,0.58
96,S97,RDC,47,23,120,23.9,18.5,0.60
97,S98,RDC,57,28,150,22.7,2.9,0.70
98,S99,RDC,89,39,276,29.2,3.0,0.41


# A. ANALYSE EXPLORATOIRE APPROFONDUE [Data analysis= EDA]

# 1. VERIFICATION DE VALEURS MANQUANTES 

In [4]:
count = df.isnull().sum()
print(count)

Semaine             0
RDC                 0
Cas_Suspects        0
Cas_Confirmes       0
Pluviometrie_mm     0
Temperature_C       0
Deforestation_ha    0
NDVI                0
dtype: int64


In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Semaine           100 non-null    object 
 1   RDC               100 non-null    object 
 2   Cas_Suspects      100 non-null    int64  
 3   Cas_Confirmes     100 non-null    int64  
 4   Pluviometrie_mm   100 non-null    int64  
 5   Temperature_C     100 non-null    float64
 6   Deforestation_ha  100 non-null    float64
 7   NDVI              100 non-null    float64
dtypes: float64(3), int64(3), object(2)
memory usage: 6.4+ KB


# 2. STATISTIQUE DESCRIPTIVE & DISTRIBUTION

In [58]:
df.describe()

,Semaine,RDC,Cas_Suspects,Cas_Confirmes,Pluviometrie_mm,Temperature_C,Deforestation_ha,NDVI
count,100.000000,100.0,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,49.500000,0.0,70.490000,32.670000,165.420000,25.847000,17.028000,0.435300
std,29.011492,0.0,16.593473,6.825465,85.116816,2.335949,8.170507,0.145626
min,0.000000,0.0,28.000000,16.000000,21.000000,22.100000,2.100000,0.210000
25%,24.750000,0.0,58.000000,29.000000,81.750000,23.900000,10.200000,0.297500
50%,49.500000,0.0,68.500000,33.000000,170.000000,26.000000,18.200000,0.445000
75%,74.250000,0.0,81.250000,37.000000,235.250000,27.850000,24.300000,0.550000
max,99.000000,0.0,115.000000,50.000000,299.000000,29.900000,29.700000,0.700000


# 2. TRANSFORMATION DES VARIABLES TEXTUELLES EN NUMERIQUES 

In [6]:
df_txt = df.select_dtypes(include=["object"])
df_txt

,Semaine,RDC
0,S01,RDC
1,S02,RDC
2,S03,RDC
3,S04,RDC
4,S05,RDC
...,...,...
95,S96,RDC
96,S97,RDC
97,S98,RDC
98,S99,RDC


In [54]:
le = LabelEncoder()
df['Semaine'] = le.fit_transform(df['Semaine'])

#columns = ['Semaine', 'RDC']                       

#for i in columns :
  #df[i] = le.fit_transform(df[i]) 

In [55]:
df

,Semaine,RDC,Cas_Suspects,Cas_Confirmes,Pluviometrie_mm,Temperature_C,Deforestation_ha,NDVI
0,0,0,59,26,122,26.5,19.7,0.38
1,1,0,98,43,290,28.2,11.5,0.26
2,2,0,74,35,126,26.0,11.8,0.46
3,3,0,58,34,91,26.2,22.3,0.58
4,4,0,79,36,208,25.4,27.1,0.31
...,...,...,...,...,...,...,...,...
95,96,0,60,31,246,26.2,10.0,0.58
96,97,0,47,23,120,23.9,18.5,0.60
97,98,0,57,28,150,22.7,2.9,0.70
98,99,0,89,39,276,29.2,3.0,0.41


# 3. LA NORMALISATION DES DONNEES 

In [21]:
df_scaler = df.copy()

cols_a_normaliser = [col for col in df.columns if col not in ['Semaine', 'RDC']]

minmax = MinMaxScaler()
df_scaler[cols_a_normaliser] = minmax.fit_transform(df[cols_a_normaliser])

df_scaler

,Semaine,RDC,Cas_Suspects,Cas_Confirmes,Pluviometrie_mm,Temperature_C,Deforestation_ha,NDVI
0,0,0,0.356322,0.294118,0.363309,0.564103,0.637681,0.346939
1,1,0,0.804598,0.794118,0.967626,0.782051,0.340580,0.102041
2,2,0,0.528736,0.558824,0.377698,0.500000,0.351449,0.510204
3,3,0,0.344828,0.529412,0.251799,0.525641,0.731884,0.755102
4,4,0,0.586207,0.588235,0.672662,0.423077,0.905797,0.204082
...,...,...,...,...,...,...,...,...
95,96,0,0.367816,0.441176,0.809353,0.525641,0.286232,0.755102
96,97,0,0.218391,0.205882,0.356115,0.230769,0.594203,0.795918
97,98,0,0.333333,0.352941,0.464029,0.076923,0.028986,1.000000
98,99,0,0.701149,0.676471,0.917266,0.910256,0.032609,0.408163


# 4. DEFINIR LES VARIABLES EXPLICATIVES & DEPENDANTE 

In [48]:
X = df_scaler.drop(['Cas_Confirmes','RDC'], axis=1)  
y = df_scaler['Cas_Confirmes']

In [49]:
X

,Semaine,Cas_Suspects,Pluviometrie_mm,Temperature_C,Deforestation_ha,NDVI
0,0,0.356322,0.363309,0.564103,0.637681,0.346939
1,1,0.804598,0.967626,0.782051,0.340580,0.102041
2,2,0.528736,0.377698,0.500000,0.351449,0.510204
3,3,0.344828,0.251799,0.525641,0.731884,0.755102
4,4,0.586207,0.672662,0.423077,0.905797,0.204082
...,...,...,...,...,...,...
95,96,0.367816,0.809353,0.525641,0.286232,0.755102
96,97,0.218391,0.356115,0.230769,0.594203,0.795918
97,98,0.333333,0.464029,0.076923,0.028986,1.000000
98,99,0.701149,0.917266,0.910256,0.032609,0.408163


In [50]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)

# 5. ENTRAINEMENT DU MODELE DE REGRESSION LINEAIRE MULTIVARIEE 

In [27]:
model_LRM = LinearRegression()
model_LRM.fit(x_train, y_train)

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [29]:
bo = (model_LRM.intercept_).round(3)
bo

np.float64(0.043)

In [51]:
coef = (model_LRM.coef_).round(3)
coef

array([-0.   ,  0.769,  0.135,  0.02 ,  0.024, -0.013])

# INTERPRETATION: Toute chose égale par ailleur,
-  Les nombres de cas suspects influencent les cas confirmés avec un taux de 0.769
- La Pluviometrie_mm influence les cas confirmés avec un taux de 0.135
-La Temperature_C influence les cas confirmés avec un taux de 0.02
- La Deforestation_ha influence les cas confirmés avec un taux de 0.024
- NDVI influence les cas confirmés avec un taux de -0.013 c.a.d le NDVI constitue un facteur protecteur pour le M-pox


# 6. PREDICTION AVEC LE MODELE 

In [38]:
y_pred = (model_LRM.predict(x_test)).round(3)
y_pred

array([0.651, 0.913, 0.206, 0.41 , 0.5  , 0.359, 0.542, 0.358, 0.433,
       0.743, 0.512, 0.814, 0.61 , 0.356, 0.403, 0.498, 0.533, 0.611,
       0.853, 0.317])

# 7. METRIQUES D'EVALUATION DE PERFORMANCE DU MODELE 

In [44]:
print("MSE",round(mean_squared_error(y_test, y_pred),3))
print("MAE",round(mean_absolute_error(y_test, y_pred),3))
print("RMSE",round(math.sqrt(mean_squared_error(y_test, y_pred)),3))
print("R2", round(r2_score(y_test, y_pred), 3))

MSE 0.009
MAE 0.067
RMSE 0.094
R2 0.772


# INTERPRETATION: 
